# Generated by Django 6.0.2 on 2026-02-15 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.court')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.round')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='teams.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='teams.team')),
            ],
        ),
    ]
