# Generated by Django 6.0.2 on 2026-02-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('teams', models.ManyToManyField(related_name='groups', to='teams.team')),
            ],
        ),
    ]
